inference_engine: "sglang"
image_name: "lmsysorg/sglang:v0.5.9" # -cu130 for H100, H200
extra_container_env: |
  - name: SGLANG_EXPERT_DISTRIBUTION_RECORDER_DIR
    value: "/dev/shm/sglang_expert_distribution_recorder"
server_start_command: |
            python3 -m moe_cap.systems.sglang \
                        --model-path @hf_model_path@ \
                        --port 30000 \
                        --expert-distribution-recorder-mode stat \
                        --tp-size @tensor_parallel_size@ @extra_server_flags@
client_run_command: |
            python3 -m moe_cap.runner.openai_api_profile \
                        --model_name @hf_model_path@ \
                        --datasets @dataset@ \
                        --num-samples @num_samples@ \
                        --api-url http://localhost:30000/v1/completions \
                        --backend sglang \
                        --ignore-eos \
                        --output_dir $RUN_DIR @extra_client_flags@
conditional_flags: 
  server_set_batch_size: "--max-running-requests @batch_size@"
  client_notify_batch_size: "--server-batch-size @batch_size@"
  