apiVersion: batch/v1
kind: Job
metadata:
  generateName: @name_k8s@-
  labels:
    kueue.x-k8s.io/queue-name:  eidf230ns-user-queue
spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: @inference_engine@-server
        image: @image_name@
        imagePullPolicy: IfNotPresent
        env:
          - name: HF_HOME
            value: /mnt/input/hf_cache
          - name: TEAS_OUTPUT_DIR
            value: /mnt/develop/outputs
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: teas-develop-results-private-ap
                key: token
          {{ extra_container_env }}
        command: ["/bin/bash", "-c"]
        args:
          - |

            timestamp=$( date +%Y%m%d-%H%M )
            RUN_DIR=/dev/shm/$timestamp
            mkdir -p $RUN_DIR
            
            exec &> $RUN_DIR/stdout_stderr.log

            @configmap_copy_job_yaml@

            job_start_time$(date +%s)
            env_start_time=$(date +%s)
            apt-get update
            apt-get -y install git
            git clone  https://github.com/Auto-CAP/MoE-CAP.git /dev/shm/MoE-CAP
            cd /dev/shm/MoE-CAP
            echo "MoE-CAP commit: " `git rev-parse HEAD`
            pip install -e .
            pip install gputil
            env_end_time=$(date +%s)
            env_duration=$((env_end_time - env_start_time))
            echo "Environment setup took $env_duration seconds" > timings.log

            server_init_start_time=$(date +%s)
            # Start server
            echo "Initialising server"
            {{ server_start_command }} &> $RUN_DIR/server.log &
            SERVER_PID=$!
            
            # Wait until the /health endpoint returns HTTP 200
            echo "Waiting for server to be ready..." 

            until curl -s -f http://localhost:30000/health > /dev/null; do
                # Check if the server has crashed (if so the health check will never succeed)
                if ! kill -0 "$SERVER_PID" 2> /dev/null; then
                    echo -e "\n[ERROR] Server proces died before becoming ready to use."
                    SERVER_STATUS="dead"
                    break
                fi

                echo -n "."
                sleep 2
            done

            if [ "$SERVER_STATUS" != "dead" ]; then
                server_init_end_time=$(date +%s)
                server_init_duration=$((server_init_end_time - server_init_start_time))
                echo "Server is ready!"
                echo "Server initialisation took $server_init_duration seconds" >> timings.log
                echo "Starting to run benchmark (sending http requests)..."

                # Start client
                client_start_time=$(date +%s)
                {{ client_run_command }} &> $RUN_DIR/client.log
                CLIENT_SUCCESS=$?  # not 100% robust, could be failed redirection
                if [ "$CLIENT_SUCCESS" == 0 ]; then
                    echo "Benchmark run finished"
                    client_end_time=$(date +%s)
                    client_duration=$((client_end_time - client_start_time))
                    echo "Client took $client_duration seconds" >> timings.log
                else
                    echo "Client crashed"
                fi
                echo "Shutting down server..."  # regardless of client success
                kill $SERVER_PID
                wait $SERVER_PID
            else
                echo "Not starting client because server is not available"
            fi            


            ##################
            # Saving results #
            ##################

            # Tidy up - gather MoE-CAP generated results from subdir
            cd $RUN_DIR
            cp @hf_model_path@/* .
            rm -r `dirname @hf_model_path@`
            mv metadata*.json metadata.json
            mv metrics*.json metrics.json
            mv detailed_results* detailed_results.jsonl
            mv output_data*.jsonl output_data.jsonl
                        
            echo "Server stopped. Copying files to pvc..."

            # Copy data out before any git commands so we have the data in case of any git issues
            RUN_OUTPUT_DIR=$TEAS_OUTPUT_DIR/@results_repo@/@output_repo_dir@/$timestamp
            mkdir -p $RUN_OUTPUT_DIR
            cp -R $RUN_DIR/* $RUN_OUTPUT_DIR/

            # We've also moved our log so change where we are writing
            exec &>> $RUN_OUTPUT_DIR/stdout_stderr.log

            echo "Files copied to pvc at $RUN_OUTPUT_DIR"

            # Move to root of output directory 
            cd $TEAS_OUTPUT_DIR/

            # Pull to refresh before committing and pushing
            cd $RUN_OUTPUT_DIR
            GIT_TOKEN="${GIT_TOKEN%$'\n'}"   # remove trailing newline that causes issues
            git pull "https://oauth2:${GIT_TOKEN}@github.com/TEAS-project/@results_repo@.git"
            
            # Commit data to results repository
            git config user.email "autopush@eidf"
            git config user.name "Pipeline Autopush"
            
            git add metrics*.json metadata*.json *.yaml
            git commit -m "auto: @name_k8s@"
            git push "https://oauth2:${GIT_TOKEN}@github.com/TEAS-project/@results_repo@.git"

            echo "Finalising container"
            job_end_time=$(date +%s)
            job_duration=$((job_end_time - job_start_time))
            echo "Job took $job_duration seconds" >> timings.log

        ports:
          - containerPort: 30000 
        resources:
          requests:
            cpu: 10
            memory: '100Gi'
          limits:
            cpu: 10
            memory: '100Gi'
            nvidia.com/gpu: @num_gpu@
        volumeMounts:
          - mountPath: /mnt/develop
            name: develop
          - mountPath: /mnt/input
            name: inputs
          - mountPath: /dev/shm
            name: dshm
          @configmap_volumeMounts@
      restartPolicy: Never
      volumes:
        - name: inputs
          persistentVolumeClaim:
            claimName: inputs-pvc
        - name: develop
          persistentVolumeClaim:
            claimName: develop-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        @configmap_volumes@
      nodeSelector:
        nvidia.com/gpu.product: @gpu_product@ 
