apiVersion: batch/v1
kind: Job
metadata:
  generateName: sglang-moe-cap-
  labels:
    kueue.x-k8s.io/queue-name:  eidf230ns-user-queue
spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      name: job-sglang-moe-cap
    spec:
      containers:
      - name: sglang-server
        image: lmsysorg/sglang:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SGLANG_EXPERT_DISTRIBUTION_RECORDER_DIR
            value: "/dev/shm/sglang_expert_distribution_recorder"
          - name: HF_HOME
            value: /mnt/input/hf_cache
          - name: HUGGINGFACE_HUB_CACHE
            value: /mnt/input/hf_cache/hub
          - name: TRANSFORMERS_CACHE
            value: /mnt/input/hf_cache/transformers
          - name: HF_DATASETS_CACHE
            value: /mnt/input/hf_cache/datasets
          - name: TEAS_OUTPUT_DIR
            value: /mnt/develop/outputs
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: teas-develop-results-private-jr
                key: git_teas_develop_results_private
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update
            apt-get -y install git
            git clone  https://github.com/Auto-CAP/MoE-CAP.git /dev/shm/MoE-CAP
            cd /dev/shm/MoE-CAP
            pip install -e .
            pip install gputil

            timestamp=$( date +%Y%m%d-%H%M )

            # Start server
            python -m moe_cap.systems.sglang \\
              --model-path @model_name@ \\
              --port 30000 \\
              --expert-distribution-recorder-mode stat \\
              --tp-size @tensor_parallel_size@ \\
              &> /dev/shm/@run_name@_$timestamp.server_log &
            SERVER_PID=$!

            # Wait until the /health endpoint returns HTTP 200
            echo "Waiting for SGLang server to be ready..."

            until curl -s -f http://localhost:30000/health > /dev/null; do
              echo -n "."
              sleep 2
            done

            echo "SGLang server is ready!"
            echo "Starting to serve bench (sending http requests)..."
            
            mkdir -p /dev/shm/@run_name@
            python -m moe_cap.runner.openai_api_profile \\
              --model_name @model_name@ \\
              --datasets @dataset@ \\
              --target-input-tokens @target_input_tokens@ \\
              --target-output-tokens @target_output_tokens@ \\
              --num-samples @num_samples@ \\
              --api-url http://localhost:30000/v1/completions \\
              --backend sglang \\
              --ignore-eos \\
              --server-batch-size @batch_size@ \\
              --output_dir /dev/shm/@run_name@ \\
              &> /dev/shm/@run_name@_$timestamp.client_log

            echo "Starting to serve bench (sending http requests)... done!"
            echo "Benchmark finished, shutting down server..."

            kill $SERVER_PID
            wait $SERVER_PID
            
            echo "Server stopped. Copying files to pvc..."

            # Moce to root of output directory

            cd $TEAS_OUTPUT_DIR

            # Clone git repo to update with results

            git clone https://oauth2:${GIT_TOKEN}@github.com/TEAS-project/TEAS_development_Results_Private.git

            RUN_OUTPUT_DIR=$TEAS_OUPUT_DIR/TEAS_development_Results_Private/SGLANG/

            # Move output data to output directory

            mkdir -p $RUN_OUTPUT_DIR
            cp -R /dev/shm/@run_name@ $RUN_OUPUT_DIR/
            cp /dev/shm/@run_name@_$timestamp* $RUN_OUPUT_DIR/

            echo "Files copied to pvc at $RUN_OUTPUT_DIR"

            # Commit data to github

            git add -A

            git commit -m "Automated output push from k8s job"

            git push https://oauth2:${GIT_TOKEN}@github.com/TEAS-project/TEAS_development_Results_Private.git

            # End of benchmark message

            echo "Finalising container"

        ports:
          - containerPort: 30000 
        resources:
          requests:
            cpu: 10
            memory: '100Gi'
          limits:
            cpu: 10
            memory: '100Gi'
            nvidia.com/gpu: @num_gpu@
        volumeMounts:
          - mountPath: /mnt/develop
            name: develop
          - mountPath: /mnt/input
            name: inputs
          - mountPath: /dev/shm
            name: dshm
      restartPolicy: Never
      volumes:
        - name: inputs
          persistentVolumeClaim:
            claimName: inputs-pvc
        - name: develop
          persistentVolumeClaim:
            claimName: develop-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      nodeSelector:
        nvidia.com/gpu.product: @gpu_product@ 
