apiVersion: batch/v1
kind: Job
metadata:
  generateName: sglang-moe-cap-
  labels:
    kueue.x-k8s.io/queue-name:  eidf230ns-user-queue
spec:
  completions: @completions@
  backoffLimit: 0
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      name: job-sglang-moe-cap
    spec:
      containers:
      - name: sglang-server
        image: lmsysorg/sglang:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SGLANG_EXPERT_DISTRIBUTION_RECORDER_DIR
            value: "/dev/shm/sglang_expert_distribution_recorder"
          - name: HF_HOME
            value: /mnt/input/hf_cache
          - name: HUGGINGFACE_HUB_CACHE
            value: /mnt/input/hf_cache/hub
          - name: TRANSFORMERS_CACHE
            value: /mnt/input/hf_cache/transformers
          - name: HF_DATASETS_CACHE
            value: /mnt/input/hf_cache/datasets
          - name: TEAS_OUTPUT_DIR
            value: /mnt/develop/outputs
          - name: TEAS_ITER_DIR
            value: /mnt/develop/iteration
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: teas-develop-results-private-jr
                key: git_teas_develop_results_private
          - name: RUN_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: ["/bin/bash", "-c"]
        args:
          - |

            # Install Git 
            apt-get update
            apt-get -y install git

            # Get MoE Cap
            git clone https://github.com/Auto-CAP/MoE-CAP.git /dev/shm/MoE-CAP
            cd /dev/shm/MoE-CAP

            pip install -e .
            pip install gputil

            # Introduce logic to replace variables

            timestamp=$( date +%Y%m%d-%H%M )

            ## On first pass touch a file          
            ## Place 0 in file
            ## This 0 represents the element in the array of row id's of the experiments csv that was last tested
            ## Each subsequent access goes to the next row in the list

            declare -i iter

            echo "check iteration director location"

            ls $TEAS_ITER_DIR

            iter_path=$TEAS_ITER_DIR/$RUN_ID

            mkdir -p $iter_path

            echo "iter path:"
            echo $iter_path

            if [[ ! -e $iter_path/iteration_file ]]; then touch $iter_path/iteration_file; iter=0; echo $iter &> $iter_path/iteration_file; else iter=$(cat $iter_path/iteration_file); fi

            ## Array of rows id's to be accessed in this test
            ## defined during template generation

            rowIds=(@line_array@)

            echo "test iteration file created"
            cat $iter_path/iteration_file

            ## Implicit start of do-while loop

            ### access next element of the array of row ids
            
            row_number="${rowIds[iter]}"

            echo "iter:"
            echo $iter
            echo "row number:"
            echo $row_number
            ### Load experiments.csv as table (in python)

            wget https://github.com/JPRichings/TEASBench/raw/refs/heads/main/MoE-Benchmark/direct-test-scripts/parameter.py

            wget https://github.com/JPRichings/TEASBench/raw/refs/heads/main/MoE-Benchmark/direct-test-scripts/data/experiments.csv

            ### select correct row and copy elements in the temp variables

            tmp_model_name=$(python3 parameter.py --csv_file=experiments.csv --parameter_name="model_name" --experiment_id=$row_number)
            tmp_tensor_parallel_size=$(python3 parameter.py --csv_file=experiments.csv --parameter_name="num_gpu" --experiment_id=$row_number) 
            tmp_dataset=$(python3 parameter.py --csv_file=experiments.csv --parameter_name="dataset" --experiment_id=$row_number)
            tmp_target_input_tokens=$(python3 parameter.py --csv_file=experiments.csv --parameter_name="target_input_tokens" --experiment_id=$row_number)
            tmp_target_output_tokens=$(python3 parameter.py --csv_file=experiments.csv --parameter_name="target_output_tokens" --experiment_id=$row_number)
            tmp_num_samples=$(python3 parameter.py --csv_file=experiments.csv --parameter_name="num_samples" --experiment_id=$row_number)
            tmp_batch_size=$(python3 parameter.py --csv_file=experiments.csv --parameter_name="batch_size" --experiment_id=$row_number)

            echo "model name" $tmp_model_name
            echo "tensor parrallel size" $tmp_tensor_parallel_size
            echo "dataset" $tmp_dataset
            echo "target_input_tokens" $tmp_target_input_tokens
            echo "target_output_tokens" $tmp_target_output_tokens
            echo "num_samples" $tmp_num_samples
            echo "batch_size" $tmp_batch_size

            # run_name="inference_engine_model_name_clean_gpuxnum_gpu_token_in_token_out_bsbatch_size_dataset"
    
            arrMN=(${tmp_model_name////})

            model_name_clean=${arrMN[1]/./} ### needs deconflicting with python f"" replacement

            run_name="sglang_$model_name_clean_$gpux$num_gpu_$tmp_target_input_tokens_$tmp_target_output_tokens_bs$tmp_batch_size_$tmp_dataset"

            # Start Sglang server
            python -m moe_cap.systems.sglang --model-path $tmp_model_name --port 30000 --expert-distribution-recorder-mode stat --tp-size $tmp_tensor_parallel_size &> /dev/shm/$run_name_$timestamp.server_log &
            SERVER_PID=$!

            # Wait until the /health endpoint returns HTTP 200
            echo "Waiting for SGLang server to be ready..."

            until curl -s -f http://localhost:30000/health > /dev/null; do
              echo -n "."
              sleep 2
            done

            echo "SGLang server is ready!"
            echo "Starting to serve bench (sending http requests)..."
            
            mkdir -p /dev/shm/$run_name
            python -m moe_cap.runner.openai_api_profile --model_name $tmp_model_name --datasets $tmp_dataset --input-tokens $tmp_target_input_tokens --output-tokens $tmp_target_output_tokens --num-samples $tmp_num_samples --config-file configs/stub.yaml --api-url http://localhost:30000/v1/completions --backend sglang --ignore-eos --server-batch-size $tmp_batch_size --output_dir /dev/shm/$run_name &> /dev/shm/$run_name_$timestamp.client_log

            echo "Starting to serve bench (sending http requests)... done!"
            echo "Benchmark finished, shutting down server..."

            kill $SERVER_PID
            wait $SERVER_PID
            
            echo "Server stopped. Copying files to pvc..."
            
            # Moce to root of output directory

            cd $TEAS_OUTPUT_DIR

            # Clone git repo to update with results

            git clone https://oauth2:${GIT_TOKEN}@github.com/TEAS-project/TEAS_development_Results_Private.git

            RUN_OUTPUT_DIR=$TEAS_OUPUT_DIR/TEAS_development_Results_Private/SGLANG/

            # Move output data to output directory

            mkdir -p $RUN_OUTPUT_DIR
            cp -R /dev/shm/$run_name $RUN_OUPUT_DIR/
            cp /dev/shm/$run_name_$timestamp* $RUN_OUPUT_DIR/

            echo "Files copied to pvc at $RUN_OUTPUT_DIR"

            # Commit data to github

            git add -A

            git commit -m "Automated output push from k8s job"

            git push https://oauth2:${GIT_TOKEN}@github.com/TEAS-project/TEAS_development_Results_Private.git


            ## Update iter file for next iteration

            if [[ iter -le ${#rowIds[@]} ]]; then
              iter+=1
              echo "updated iter:"               
              echo $iter
              echo $iter > $iter_path/iteration_file
              echo "iteration count incremented:"
              cat $iter_path/iteration_file
            else
              echo "end of iterations"
            fi

            # End of benchmark message

            echo "Files copied, end of iteration, exiting container"

        ports:
          - containerPort: 30000 
        resources:
          requests:
            cpu: 10
            memory: '100Gi'
          limits:
            cpu: 10
            memory: '100Gi'
            nvidia.com/gpu: @num_gpu@
        volumeMounts:
          - mountPath: /mnt/develop
            name: develop
          - mountPath: /mnt/input
            name: inputs
          - mountPath: /dev/shm
            name: dshm
      restartPolicy: Never
      volumes:
        - name: inputs
          persistentVolumeClaim:
            claimName: inputs-pvc
        - name: develop
          persistentVolumeClaim:
            claimName: develop-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      nodeSelector:
        nvidia.com/gpu.product: @gpu_product@
