#!/bin/python3

import base64
import io
import pathlib
import textwrap

import pandas as pd

from utils import MODEL_DISK_GB_MAP, VAST_GPU_MAP

# A rented Vast.ai host's driver must support a minimum CUDA version that is compatible with
# the version in the base images in pipeline/vast/*/Dockerfile (currently vllm/vllm-openai:v0.16.0, which uses 12.9).
# Note that I've observed that sometimes the version specified in an offer doesn't appear to be accurate; in this case,
# cancel and start with a new offer. (I will have run_benchmark.sh note if this is spotted in server logs.)
MIN_CUDA_VERSION = "12.9"


def _image_for_engine(engine):
    """
    Return the image name depending on the inference engine we're using.
    """
    if engine == "vllm":
        return "ghcr.io/teas-project/vllm-bench:latest"
    if engine == "sglang":
        return "ghcr.io/teas-project/sglang-bench:latest"
    raise ValueError(f"Unknown inference engine: {engine!r}")


def _encode_csv_group(group_df, all_columns):
    """
    Encode the whole input CSV with base64 and return it.
    """
    buf = io.StringIO()
    group_df[all_columns].to_csv(buf, index=False)
    return base64.b64encode(buf.getvalue().encode()).decode()


def _generate_script(engine, gpu, num_gpu, disk_gb, encoded_csv, registry_login: tuple | None = None):
    """
    Generate a bash script for launching a Vast.ai instance with the specified engine, GPU, and number of GPUs.
    We pass the encoded CSV containing the benchmarks to run through to it as a environment variable.
    We rely on:
    1) the user having installed the Vast.ai CLI locally
    2) the image being accessible (i.e. public or user adds authorisation to pull it)
    3) the GIT_TOKEN, HF_TOKEN, OPENAI_API_KEY secrets set in Vast.ai
    """
    vast_gpu = VAST_GPU_MAP[gpu]
    image = _image_for_engine(engine)

    # Add the option to provide registry login info, if it was previously provided as an argument.
    # The user must do this if the image is private, wherever it's being kept.
    login_line = ""
    if registry_login is not None:
        username, password, registry = registry_login
        login_line = f"\n          --login '-u {username} -p {password} {registry}' \\"

    # Otherwise, just return the contents of the script.
    # The --args (with nothing following) argument is required to put the instance into args/entrypoint launch mode;
    # without it, vastai defaults to injecting its own SSH server instead of going to the image's ENTRYPOINT.
    return textwrap.dedent(f"""\
        #!/usr/bin/env bash
        # Vast.ai launch script — {engine} on {gpu}x{num_gpu}
        # Generated by generate.py --vast
        #
        # Prerequisites:
        #   - vastai CLI installed and authenticated (vastai login)
        #   - Container image pushed to an accessible registry
        #   - The following environment variables must be set as secrets in Vast.ai:
        #       GIT_TOKEN, HF_TOKEN, OPENAI_API_KEY

        BENCHMARK_CSV="{encoded_csv}"

        # 1. Search for available offers matching the hardware requested from the CSV.
        #    cuda_vers filters out hosts whose driver is too old for the image's CUDA
        #    build (otherwise the server dies on GPU init with a cudaGetDeviceCount error).
        #    Offers will be sorted by dollars per hour rental cost, increasing.
        vastai search offers 'gpu_name={vast_gpu} num_gpus={num_gpu} verified=true rentable=true cuda_vers>={MIN_CUDA_VERSION}' -o 'dph+'

        # 2. Prompt for an offer ID from the results above.
        read -rp "Enter offer ID: " OFFER_ID

        # 3. Launch the instance.
        vastai create instance "$OFFER_ID" \\
          --image "{image}" \\
          --disk {disk_gb} \\{login_line}
          --env "-e BENCHMARK_CSV=${{BENCHMARK_CSV}}" \\
          --args
    """)


def generate_vast_scripts(csv_file, target_dir, registry_login: tuple | None = None):
    pathlib.Path(target_dir).mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(csv_file)
    all_columns = list(df.columns)

    # Loop through groups from the dataframe based on the engine-gpu-num_gpu triple.
    # This way we're automatically going to build an encoded CSV for each triple alone (by which I mean not including
    # the rows for other inference engines / GPU configs).
    for (engine, gpu, num_gpu), group in df.groupby(["inference_engine", "gpu", "num_gpu"]):
        if gpu not in VAST_GPU_MAP:
            raise ValueError(
                f"GPU {gpu!r} not in VAST_GPU_MAP. Add it to pipeline/utils.py."
            )

        # Size the instance's disk to the largest model in this group, since the model
        # weights are downloaded onto it (into the HF cache).
        disk_gb = max(MODEL_DISK_GB_MAP[model] for model in group["model"].unique())

        # Generate the encoded CSV for this engine-gpu-num_gpu triplet and then write the
        # script to submit this to a Vast.ai instance.
        encoded_csv = _encode_csv_group(group, all_columns)
        script = _generate_script(engine, gpu, num_gpu, disk_gb, encoded_csv,
                                  registry_login=registry_login)

        # Write the script and for convenience make it executable right away.
        out_path = pathlib.Path(target_dir) / f"vast_{engine}_{gpu}x{num_gpu}.sh"
        out_path.write_text(script)
        out_path.chmod(0o755)
        print(f"Generated {out_path}  ({len(group)} benchmark row(s))")
