apiVersion: batch/v1
kind: Job
metadata:
  generateName: pvc-helper-job
  labels:
    kueue.x-k8s.io/queue-name: eidf230ns-user-queue
spec:
  completions: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      name: pvc-helper-pod-inputs-pvc
    spec:
      containers:
      - name: cudasample
        image: python:3.10-slim
        args: ["sleep", "infinity"]
        resources:
          requests:
            cpu: 2
            memory: '1Gi'
          limits:
            cpu: 2
            memory: '4Gi'
        volumeMounts:
          - mountPath: /mnt/input
            name: inputs
      restartPolicy: Never
      volumes:
        - name: inputs
          persistentVolumeClaim:
            claimName: inputs-pvc
